name: Download Model from Hugging Face

on:
  workflow_dispatch:

jobs:
  download-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        lfs: true

    - name: Install Git LFS
      run: |
        git lfs install

    - name: Download GGUF model
      run: |
        git clone https://huggingface.co/ahmedheakl/arazn-llama3-arabic-gguf

    - name: Track with Git LFS and Push
      run: |
        git lfs track "*.gguf"
        git add .gitattributes
        git add arazn-llama3-arabic.Q4_K_M.gguf
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git commit -m "Add GGUF model from HuggingFace"
        git push origin main
