name: Download and Push GGUF Model

on:
  workflow_dispatch:

jobs:
  download-and-push:
    runs-on: ubuntu-latest

    env:
      MODEL_URL: https://huggingface.co/TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF/resolve/main/tinyllama-1.1b-chat-v1.0.Q8_0.gguf?download=true
      MODEL_FILE: tinyllama-1.1b-chat-v1.0.Q8_0.gguf

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_PAT }}

    - name: Install Git LFS
      run: |
        sudo apt-get update
        sudo apt-get install git-lfs -y
        git lfs install

    - name: Download GGUF model
      run: |
        wget -O "$MODEL_FILE" "$MODEL_URL"

    - name: Track GGUF file with Git LFS
      run: |
        git lfs track "*.gguf"
        git add .gitattributes

    - name: Commit and Push to GitHub
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add .
        git commit -m "Add TinyLlama GGUF model"
        git push origin main
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
