services:
  - type: web
    name: tinyllama-telegram-bot
    runtime: python
    pythonVersion: 3.10.13   # ← مهم جداً
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python llama_telegram_bot.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ALLOWED_USER_ID
        sync: false
    plan: starter
    repo: issa261/github-workflows-download-model.yml
    branch: main
    autoDeploy: true
