name: Download GGUF Model from Hugging Face

on:
  workflow_dispatch:

jobs:
  download-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Set up Git LFS
        run: |
          git lfs install

      - name: Download the GGUF model file directly
        run: |
          wget https://huggingface.co/ahmedheakl/arazn-llama3-arabic-gguf

      - name: Track with Git LFS and commit
        run: |
          git lfs track "*.gguf"
          git add .gitattributes
          git add arazn-llama3-arabic.Q4_K_M.gguf
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit -m "Add GGUF model from HuggingFace"
          git push origin main
