jobs:
  download-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Download GGUF model
        run: |
          wget -O arazn-llama3-arabic-gguf-unsloth.Q4_K_M.gguf https://huggingface.co/ahmedheakl/arazn-llama3-arabic-gguf/resolve/main/arazn-llama3-arabic-gguf-unsloth.Q4_K_M.gguf

      - name: Setup Git identity
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Track large files with Git LFS
        run: |
          git lfs install
          git lfs track "*.gguf"

      - name: Commit and push model
        run: |
          git add .
          git commit -m "Add Arazn Arabic LLaMA3 GGUF model"
          git push origin main
