name: Download and Push GGUF Model

on:
  workflow_dispatch:  # تشغيل يدويًا من واجهة GitHub

jobs:
  download-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Download GGUF model
        run: |
          wget -O arazn-llama3-arabic-gguf-unsloth.Q4_K_M.gguf \
          "https://huggingface.co/ahmedheakl/arazn-llama3-arabic-gguf/resolve/main/arazn-llama3-arabic-gguf-unsloth.Q4_K_M.gguf?download=true"

      - name: Track GGUF file with Git LFS
        run: |
          git lfs install
          git lfs track "*.gguf"
          echo "*.gguf filter=lfs diff=lfs merge=lfs -text" >> .gitattributes

      - name: Commit and Push
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git add .
          git commit -m "Add Arazn Arabic LLaMA3 GGUF model"
          git remote set-url origin https://${GH_PAT}@github.com/${{ github.repository }}
          git push origin main
